### ISSUE TITLE
Mulighet for å bygge flere image typer og flere tags. 

### ISSUE THREAD

**Issue by mrsladek** [nais/docker-build-push#2]
Hei, 
Kjempe initiativ med egen action! Her kommer noe forslag fra min siden. 
Ville det være mulig å bygge images for forskjellige platform, få støtte for flere tags og pulle underliggende images?

Vi bruke noe slik per i dag og ser at dere bruker **docker/build-push-action@v4** under panseret også så jeg regner med at det blir mulig å etablere noe sånt.

```      
      - name: Set up QEMU
        if: inputs.build-image
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: inputs.build-image
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        if: inputs.build-image
        uses: docker/build-push-action@v4
        with:
          context: .
          **platforms: linux/amd64, linux/arm64** # støtte både for Intel og Apple
          **pull: true** # greit med en pull slit at underliggende images får en update
          push: ${{ inputs.push-image }}
          **tags: app:tag1, app:latest** # støtte for flere tags
          cache-from: type=gha
          cache-to: type=gha,mode=max
```
